---
title: "Untitled"
author: "Boseong Yun"
date: "5/22/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Library
library(tidymodels)
library(tidyverse)
library(knitr)
library(lfe)
library(huxtable)
library(stargazer)
```


```{r}
# Reading results
log_res_list <- readRDS("log_res_list_filtered.rds")
las_res_list <- readRDS("las_res_list_filtered.rds")
rf_res_list <- readRDS("rf_res_list_filtered.rds")
```

# Saving the Metrics Results (set to roc_auc)

```{r}
# Region Names 
region_names <- c("Southeast Asia", "Central Asia & the Caucasus", "East Asia", "South Asia", "Europe", "Latin America & the Caribbean", "Middle East", "Africa")

# Logistic Metrics Result 
log_metrics <- log_res_list %>%
  map(collect_metrics) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  filter(.metric == "roc_auc") %>%
  ungroup()

# Lasso best results
lasso_best <- list()

for(i in seq_along(las_res_list)) {
  
  lasso_best[[i]] <- select_best(las_res_list[[i]], "roc_auc")
  
}

lasso_best_metrics <- lasso_best %>%
  set_names(region_names) %>%
  bind_rows(.id = "region")


# Lasso Metrics Result 
las_metrics <- las_res_list %>%
  map(collect_metrics) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  filter(.metric == "roc_auc") %>%
  inner_join(lasso_best_metrics)


# Random Forest best results
rf_best <- list()

for(i in seq_along(rf_res_list)) {
  
  rf_best[[i]] <- select_best(rf_res_list[[i]][[1]], "roc_auc")
  
}

rf_best_metrics <- rf_best %>%
  set_names(region_names) %>%
  bind_rows(.id = "region")


# RF normal res
rf_res <- list()

for(i in seq_along(rf_res_list)) {
  
  rf_res[[i]] <- rf_res_list[[i]][[1]]
}

# Logistic Metrics Result 
rf_metrics <- rf_res %>%
  map(collect_metrics) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  filter(.metric == "roc_auc") %>%
  inner_join(rf_best_metrics)
```


# Pulling the tuned hyperparameters for Lasso and Random Forest (based on roc_auc)


# huxtable(https://cran.r-project.org/web/packages/huxtable/vignettes/huxtable.html)

```{r}
# Saving the tuned parameters for lasso
las_params <- las_metrics %>% dplyr::select(region, penalty, .config)

# Saving the tuned parameters for random forest
rf_params <- rf_metrics %>% dplyr::select(region, mtry, min_n, .config)

# params_table
params_table <- las_params %>%
  select(-.config) %>%
  left_join(rf_params) %>%
  select(-.config) %>%
  set_names(str_to_title(names(.)))

# Huxtable
params_table %>%
  hux() %>%
  set_all_borders(TRUE) %>%
  set_bold(row = 1, col = everywhere) %>%
  set_caption("Tuned Hyper-Parameters for Lasso and Random Forest Models") %>%
  quick_docx(file = "param_table.docx")
```

# Filtering data to optimized parametrs

```{r}
## Filtering data to optimized parameters ## 
log_results <- log_res_list %>%
  map(collect_metrics) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  group_by(region, .metric) %>%
  filter(mean == max(mean)) %>%
  ungroup()

las_results <- las_res_list %>%
  map(collect_metrics) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  inner_join(lasso_best_metrics)

rf_results <- rf_res %>%
  map(collect_metrics) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  inner_join(rf_best_metrics)
```


```{r}
# Finding the best results conditioning on the tuned parameters

find_best <- function(data) {
  
  # Save the metrics
  selected_metrics <- deparse(substitute(metrics))
  
  # 
  selected_df <- data %>%
    group_by(region, .metric) %>%
    filter(mean == max(mean))
  
  # return
  return(selected_df)
}


# Tuned Average Accuracy Rates
los_acc <- find_best(log_results) %>% 
  filter(.metric == "accuracy") %>%
  ungroup() %>%
  select(region, mean) %>%
  set_names(c("Region", "Logistic Regression"))

las_acc <- find_best(las_results) %>% 
  filter(.metric == "accuracy") %>%
  ungroup() %>%
  select(region, mean) %>%
  set_names(c("Region", "Lasso Regression"))

rf_acc <- find_best(rf_results) %>% 
  filter(.metric == "accuracy") %>%
  ungroup() %>%
  select(region, mean) %>%
  set_names(c("Region", "Random Forest"))

# Average
acc_avg <- los_acc %>%
  left_join(las_acc) %>%
  left_join(rf_acc) %>%
  arrange(Region) %>%
  summarize_at(vars(-Region), mean) %>%
  mutate(Region = "Average")


# Accuracy Results
los_acc %>%
  left_join(las_acc) %>%
  left_join(rf_acc) %>%
  arrange(Region) %>%
  bind_rows(acc_avg) %>%
  hux() %>%
  set_all_borders(TRUE) %>%
  set_bold(row = 1, col = everywhere) %>%
  set_caption("Predictive Accuracy Rate by Model") %>%
  quick_docx(file = "accuracy_table.docx")


```

# AUC

```{r}
# Tuned Average Accuracy Rates
los_auc <- find_best(log_results) %>% 
  filter(.metric == "roc_auc") %>%
  ungroup() %>%
  select(region, mean) %>%
  set_names(c("Region", "Logistic Regression"))

las_auc <- find_best(las_results) %>% 
  filter(.metric == "roc_auc") %>%
  ungroup() %>%
  select(region, mean) %>%
  set_names(c("Region", "Lasso Regression"))

rf_auc <- find_best(rf_results) %>% 
  filter(.metric == "roc_auc") %>%
  ungroup() %>%
  select(region, mean) %>%
  set_names(c("Region", "Random Forest"))

# Summary
auc_avg <- los_auc %>%
  left_join(las_auc) %>%
  left_join(rf_auc) %>%
  arrange(Region) %>%
  summarize_at(vars(-Region), mean) %>%
  mutate(Region = "Average")


# AUC Results
los_auc %>%
  left_join(las_auc) %>%
  left_join(rf_auc) %>%
  arrange(Region) %>%
  bind_rows(auc_avg) %>%
  hux() %>%
  set_all_borders(TRUE) %>%
  set_bold(row = 1, col = everywhere) %>%
  set_caption("Area Under the Curve by Model") %>%
  quick_docx(file = "auc.docx")
```



# Conf Mat

```{r}
# Logistic Model
log_predictions <- log_res_list %>%
  map(collect_predictions) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region")

log_predictions %>%
  conf_mat(woman, .pred_class) %>%
  tidy() %>%
  mutate(prop = value / sum(value),
         prop = prop * 100)
```


```{r}
# Lasso Model
las_predictions <- las_res_list %>%
  map(collect_predictions) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  inner_join(las_params)

las_predictions %>%
  conf_mat(woman, .pred_class) %>%
  tidy() %>%
  mutate(prop = value / sum(value),
         prop = prop * 100)

# Random Forest Model
rf_predictions <- rf_res %>%
  map(collect_predictions) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  inner_join(rf_params)

rf_predictions %>%
  conf_mat(woman, .pred_class) %>% 
  tidy() %>%
  mutate(prop = value / sum(value),
         prop = prop * 100)
```

# ROC_AUC CURVE

```{r}
log_fig <- log_predictions %>%
  group_by(region) %>%
  roc_curve(woman, .pred_0) %>%
  autoplot() +
  labs(
    title = "Figure 1-1. The Average ROC Curve For Logistic Regression",
    x = "1 - Specificity",
    y = "Sensitivity",
    color = "Region"
  ) +
  theme(text = element_text(size = 20, family = "Calibri"))

las_fig <- las_predictions %>%
  group_by(region) %>%
  roc_curve(woman, .pred_0) %>%
  autoplot() +
  labs(
    title = "Figure 1-2. The Average ROC Curve For Lasso Regression",
    x = "1 - Specificity",
    y = "Sensitivity",
    color = "Region"
  ) +
  theme(text = element_text(size = 20, family = "Calibri"))

rf_fig <- rf_predictions %>%
  group_by(region) %>%
  roc_curve(woman, .pred_0) %>%
  autoplot() +
  labs(
    title = "Figure 1-3. The Average ROC Curve For Random Forest",
    x = "1 - Specificity",
    y = "Sensitivity",
    color = "Region"
  ) +
  theme(text = element_text(size = 20, family = "Calibri"))


```

```{r}
# Random Forest Final Fit
rf_final_res <- list()

for(i in seq_along(rf_res_list)) {
  
  rf_final_res[[i]] <- rf_res_list[[i]][[2]]
  
}

# Random Forest Final Model
rf_final_res %>%
  map(collect_metrics) %>%
  set_names(region_names) %>%
  bind_rows(.id = "region") %>%
  pivot_wider(names_from = .metric, 
              values_from = .estimate) %>%
  dplyr::select(region, accuracy, roc_auc) %>%
  set_names(str_to_title(names(.))) %>%
  arrange(Region) %>%
  hux() %>%
  set_all_borders(TRUE) %>%
  set_bold(row = 1, col = everywhere) %>%
  set_caption("Area Under the Curve by Model") %>%
  quick_docx(file = "final.docx")
``` 

# Panel


```{r}
# Combining the panel data
total <- africa_df %>%
  bind_rows(central_asia_df) %>%
  bind_rows(east_asia_df) %>%
  bind_rows(south_asia_df) %>%
  bind_rows(southeast_asia_df) %>%
  bind_rows(europe_df) %>%
  bind_rows(latin_df) %>%
  bind_rows(middle_df)

# Panel data for women
total_woman <- total %>%
  filter(woman == 1) %>%
  dplyr::select(-woman) %>%
  group_by(country, year, sub_event_type, inter1, inter2) %>%
  summarize(
    count = n(),
    fatalities = mean(fatalities)
  )

# Panel data for men
total_man <- total %>%
  filter(woman == 0) %>%
  dplyr::select(-woman) %>%
  group_by(country, year, sub_event_type, inter1, inter2) %>%
  summarize(
    count = n(),
    fatalities = mean(fatalities)
  )

```


```{r}
# Fixed Effects Models for men and women seperatley
woman <- felm(count ~ sub_event_type + inter1 + inter2 + fatalities | country + year | 0 | country, data = total_woman)

man <- felm(count ~ sub_event_type + inter1 + inter2 + fatalities | country + year | 0 | country, data = total_man)
```

```{r}
# Saving the name of the coefficients
coef_terms_raw <- man %>%
  tidy() %>% 
  mutate(term = str_remove_all(term, pattern = "sub_event_type")) %>%
  dplyr::select(term)

# Saving the names of the coefficients for actors
inter1_name <- paste("Actor 1:", c("Rebel Groups", "Political Militias",
                 "Identity Militias", "Rioters", "Protesters", "Cvilians",
                 "External / Other Forces"))

inter2_name <- paste("Actor 2:", c("State Forces", "Rebel Groups", "Political Militias",
                 "Identity Militias", "Rioters", "Protesters", "Cvilians",
                 "External / Other Forces"))

# Save intutive terms
coef_terms_raw[25:39, ] <- c(inter1_name, inter2_name)

# View
coef_names <- coef_terms_raw %>% 
  mutate(term = str_to_title(term)) %>%
  pull()
```


```{r}
# Stargazer
stargazer(man, woman, header = FALSE, type = "html", 
          dep.var.labels = "Total Events",
          column.labels = c("Man", "Woman"),
          covariate.labels = coef_names, 
          out = "panel_res2.html")
```



