---
title: "Untitled"
author: "Boseong Yun"
date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading Libraries
library(tidymodels)
library(tidyverse)
library(lubridate)
library(here)
library(MASS)
library(klaR)
library(discrim)
library(lfe)
library(plm)
library(themis)
library(baguette)
```

# Pre-Processing

```{r}
# Importing women targeting violence data
women <- read_csv(here("CSV/gender_Apr09.csv")) %>%
  set_names(str_to_lower(names(.))) %>%
  dplyr::select(-starts_with(c("admin", "source"))) 


read_data <- function(data) {
  
  # data
  file_name <- deparse(substitute(data)) 
  
  # filter
  df <- read_csv(here(data)) %>%
    set_names(str_to_lower(names(.))) %>%
    mutate(event_date2 = lubridate::dmy(event_date)) %>%
    filter(year > 2017) %>%
    filter(event_date2 < lubridate::ymd(20210401))
  
  # return
  return(df)
  
}

africa <- read_data("CSV/Africa_1997-2021_Apr16.csv")
central_asia <- read_data("CSV/CCA_2017-2021_Apr16.csv")
east_asia <- read_data("CSV/East-Asia_2018-2021_Apr09.csv")
south_asia <- read_data("CSV/South-Asia_2010-2021_Apr09.csv")
southeast_asia <- read_data("CSV/Southeast-Asia_2010-2021_Apr09updated.csv")
europe <- read_data("CSV/Europe_2018-2021_Apr09.csv")
latin <- read_data("CSV/LatinAmerica_2018-2021_Apr16.csv")
middle <- read_data("CSV/MiddleEast_2015-2021_Apr16.csv")

```


```{r}
clean_data2 <- function(data) {
  
  # Saving the names of countires
  selected_countries <- unique(data$country)
  
  # Creating a women_df: filterted the countries to africa and created the woman variable
  women_df <- women %>%
    filter(country %in% selected_countries) %>%
    mutate(woman = 1)
  
  # Joining the dataframe
  merged <- data %>%
    left_join(women_df) %>%
    mutate(woman = factor(ifelse(is.na(woman) == TRUE, 0, woman))) %>%
    dplyr::select(country, year, sub_event_type, fatalities, woman, inter1, inter2) %>%
    mutate_at(vars(year, inter1, inter2), as.factor)
  
  # small_obs
  small_obs <- merged %>%
    count(country) %>%
    filter(n < 100) %>%
    pull(country)
  
  # Filtered out
  merged2 <- merged %>%
    filter(!(country %in% small_obs))
  
  # Return the data
  return(merged2)
  
}

```


```{r}
# Cleaning the data
africa_df <- clean_data2(africa)
central_asia_df <- clean_data2(central_asia)
east_asia_df <- clean_data2(east_asia)
south_asia_df <- clean_data2(south_asia)
southeast_asia_df <- clean_data2(southeast_asia)
europe_df <- clean_data2(europe)
latin_df <- clean_data2(latin)
middle_df <- clean_data2(middle)
```




```{r logistic}
# Checking Logistic Results 
check_log <- function(data) {
  
  # setting seed
  set.seed(1231)
  
  # Creating a random split (0.8)
  split <- initial_split(data, prop = 0.8)
  
  # split into training/test 
  train <- training(split)
  test <- testing(split)
  
  # cross validation split
  val_splits <- vfold_cv(v = 5, data = train)
  
  # Creating a vector of country name
  con_name <- as.character(substitute(data)) %>%
    str_remove_all("_df")
  
  # creating a recipe
  recipe <- recipe(woman ~., data = train) %>%
    step_dummy(all_predictors(), -fatalities) %>%
    step_smote(woman)
  
  # Specifying the model
  mod_logistic <- logistic_reg() %>%
    set_engine("glm") %>%
    set_mode("classification")
  
  # workflow
  glm_res <- workflow() %>%
    add_recipe(recipe) %>%
    add_model(mod_logistic) %>%
    fit_resamples(
      resamples = val_splits,
      metrics = metric_set(roc_auc, accuracy, sensitivity, specificity, recall),
      control = control_resamples(save_pred = TRUE)
    ) %>%
  mutate(country = con_name)
  
  # Return the logistic result
  return(glm_res)
  
}


# Saving the results
log_results_sea <- check_log(southeast_asia_df)
log_results_ca <- check_log(central_asia_df)
log_results_ea <- check_log(east_asia_df)
log_results_sa <- check_log(south_asia_df)
log_results_eu <- check_log(europe_df)
log_results_lt <- check_log(latin_df)
log_results_md <- check_log(middle_df)
log_results_af <- check_log(africa_df)

# Saving all the results 
log_res_list <- list(
  log_results_sea,
  log_results_ca,
  log_results_ea,
  log_results_sa,
  log_results_eu,
  log_results_lt,
  log_results_md,
  log_results_af
)

log_res_list %>%
  saveRDS("log_res_list_filtered.rds")
```


```{r lasso}
check_lasso <- function(data) {
  
  # setting seed
  set.seed(1231)
  
  # Creating a random split (0.8)
  split <- initial_split(data, prop = 0.8)
  
  # split into training/test 
  train <- training(split)
  test <- testing(split)
  
  # cross validation split
  val_folds <- vfold_cv(train, v = 5)
  
  # Creating a vector of country name
  con_name <- as.character(substitute(data)) %>%
    str_remove_all("_df")
  
  # creating a recipe
  recipe <- recipe(woman ~., data = train) %>%
    step_dummy(all_predictors(), -fatalities) %>%
    step_smote(woman)
  
  # Specifying the model
  las_tune_spec <- logistic_reg(
    penalty = tune(),
    mixture = 1 # lasso
  ) %>%
    set_engine("glmnet")
  
  # Specifying the workflow
  las_wf <- workflow() %>%
    add_recipe(recipe) %>%
    add_model(las_tune_spec)
  
  # Specifying the lambda gridLamda grid
  lambda_grid <- grid_regular(
    penalty(range = c(-5, 1)),
    levels = 50
  )
  
  # Saving the tuned results
  las_tune_res <- tune_grid(
    las_wf,
    resamples = val_folds,
    grid = lambda_grid,
    metrics = metric_set(roc_auc, accuracy, sensitivity, specificity, recall),
    control = control_resamples(save_pred = TRUE)
  )
  
  # Return the logistic result
  return(las_tune_res)
  
}


# Saving the results
las_results_sea <- check_lasso(southeast_asia_df)
las_results_ca <- check_lasso(central_asia_df)
las_results_ea <- check_lasso(east_asia_df)
las_results_sa <- check_lasso(south_asia_df)
las_results_eu <- check_lasso(europe_df)
las_results_lt <- check_lasso(latin_df)
las_results_md <- check_lasso(middle_df)
las_results_af <- check_lasso(africa_df)

las_res_list <- list(
  las_results_sea,
  las_results_ca,
  las_results_ea,
  las_results_sa,
  las_results_eu,
  las_results_lt,
  las_results_md,
  las_results_af
)

las_res_list %>%
  saveRDS("las_res_list_filtered.rds")
```

```{r rf}
doParallel::registerDoParallel()

check_rf <- function(data) {
  
  # setting seed
  set.seed(1231)
  
  # Creating a random split (0.8)
  split <- initial_split(data, prop = 0.8)
  
  # split into training/test 
  train <- training(split)
  test <- testing(split)
  
  # cross validation split
  val_splits <- vfold_cv(v = 5, data = train)
  
  # Creating a vector of country name
  con_name <- as.character(substitute(data)) %>%
    str_remove_all("_df")
  
  # creating a recipe
  recipe <- recipe(woman ~., data = train) %>%
    step_dummy(all_predictors(), -fatalities) %>%
    step_smote(woman)
  
  # Specifying the model
  rf_tune_spec <- rand_forest(
    mtry = tune(),
    trees = 1000,
    min_n = tune()
    ) %>%
    set_mode("classification") %>%
    set_engine("ranger")
  
  # Specifying the workflow
  rf_wf <- workflow() %>%
    add_recipe(recipe) %>%
    add_model(rf_tune_spec)
  
  # Specifying the grid
  my_grid <- grid_regular(
    min_n(range = c(20, 30)),
    mtry(range = c(1, 8)),
    levels = 5
  )
  
  # Saving the tuned results
  rf_tune_res <- tune_grid(
    rf_wf,
    resamples = val_splits,
    grid = my_grid,
    metrics = metric_set(roc_auc, accuracy, sensitivity, specificity, recall),
    control = control_resamples(save_pred = TRUE)
  )

  # Best auc
  best_auc <- select_best(rf_tune_res, "roc_auc")
  
  # Final model
  final_rf <- finalize_model(
    rf_tune_spec,
    best_auc
  )
  
  # final workflow
  final_wf <- workflow() %>%
    add_recipe(recipe) %>%
    add_model(final_rf)
  
  # Final res
  final_res <- final_wf %>%
    last_fit(split)
  
  # Return the logistic result
  result <- list(rf_tune_res, final_res)
  
  # return
  return(result)
}


# Saving the results
rf_results_sea <- check_rf(southeast_asia_df)
rf_results_ca <- check_rf(central_asia_df)
rf_results_ea <- check_rf(east_asia_df)
rf_results_sa <- check_rf(south_asia_df)
rf_results_eu <- check_rf(europe_df)
rf_results_lt <- check_rf(latin_df)
rf_results_md <- check_rf(middle_df)
rf_results_af <- check_rf(africa_df)

rf_res_list <- list(
  rf_results_sea,
  rf_results_ca,
  rf_results_ea,
  rf_results_sa,
  rf_results_eu,
  rf_results_lt,
  rf_results_md,
  rf_results_af
)

rf_res_list %>%
  saveRDS("rf_res_list_filtered.rds")
```


